### ISSUE TITLE
Request for Insight on "Error Bypass.dump"

### ISSUE THREAD

**Issue by skylandersNFC** [Texthead1/Skylander-IDs#1]
Hi Texthead,

Apologies for reaching out here and potentially bothering you - I tried contacting you on Discord but couldn’t get through.

I’ve come across something called "Error Bypass.dump" circulating in a few channels.
From what I’ve gathered through trial and error, it seems to exploit a way to overload the portal thread, enabling the sideloading of previous dumps onto the portal without requiring signature checks.

While I’ve managed to piece together a basic understanding of how it works, I’d really like to dive deeper into its functionality.

For instance, I wasn’t able to successfully load an Imaginators dump that included character progress.
Instead, I keep getting the default "clean" LVL1 version.
It seems like the portal only utilizes the initialization block and disregards any additional data.

I heard that you discovered this glitch a while back and was hoping you could share some insights or guidance.

Thank you so much for your time and help!

Best regards

**Comment by Texthead1** [comment]
Hi there. The error bypass dump is a reskin of a dump I created a while ago to load Heartbreaker Buckshot into Imaginators. The method it uses does work for all other figures, with the caveat being it’ll act as a “ghost tag”, so the Portal will not read any successful data from the figure nor write any of it back.

The way it works isn’t due to overloading the Portal thread, but instead due to a memory allocation issue if both the RAM of the game and the “RAM” (figure indices cached in the Portal’s memory) are synced up correctly. If the figure index for the error bypass dump correlates to the exact same figure index of a previous figure (of which’s ID will remain cached), when the game processes the tag header, it fails to correctly read the rest of this tag and incidentally ends up pulling the data from that very cached figure.

This happens due to a small exploit and issue regarding byte 0x13 of the figure/tag header. When this is not 0, the game is meant to reject the figurine, but this is only functionally complete in SSA, SG, and STT. In SSF, SSC, and SI, it’ll do the undefined behaviour as stated.

Aligning the figure indices of the Portal is much easier using an emulated portal, as all you need to do is load the new tag in the same slot as the previous one. However, for use with physical Portals, you can reset the figure indices either by sending commands to it using software, whilst the game is interacting with it, or simply unplug and replug the Portal before scanning the first tag to put it in slot 0, and repeat for the second tag.

If any additional information is required, you may be able to find it here: 
https://github.com/Texthead1/Runes/blob/master/Docs/SkylanderFormat.md#error-byte

**Comment by skylandersNFC** [comment]
Thank you kindly, that was a killer answer :)
